version: "3.8"

volumes:
  db_data:

networks:
  common-net:

x-db-credentials: &db-credentials
  POSTGRES_USER: envmon_user
  POSTGRES_PASSWORD: envmon_password
  POSTGRES_DB: envmon_database

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: envmon_database
  DATABASE_USERNAME: envmon_user
  DATABASE_PASSWORD: envmon_password
  NODE_ENV: development

services:
  app:
    build: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks: ["common-net"]
    command: ["npm", "start"]

  migrate:
    build: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks: ["common-net"]
    command: ["npm", "run", "migrate"]
    deploy:
      replicas: 0

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U envmon_user -d envmon_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks: ["common-net"]
