volumes:
  db_data:

networks:
  common-net:

# Define all database-related variables in one place
x-db-credentials: &db-credentials
  POSTGRES_USER: envmon_user
  POSTGRES_PASSWORD: envmon_password
  POSTGRES_DB: envmon_database

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: envmon_database
  DATABASE_USERNAME: envmon_user
  DATABASE_PASSWORD: envmon_password

services:
  app:
    image: envmon-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks: ["common-net"]
    command: ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]

  migrate:
    image: envmon-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks: ["common-net"]
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: envmon-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks: ["common-net"]
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U envmon_user -d envmon_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    networks: ["common-net"]
